version: '3.2'

services:
  reverseproxy:
    image: nginx:latest
    depends_on:
      - codescene    
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/error.log:/etc/nginx/error_log.log

  codescene:
    image: empear/ubuntu-onprem:latest
    restart: always
    environment:
      - GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    volumes:
      - ~/codescene:/codescene
      - ~/.ssh:/root/.ssh
